name: Gatsby.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - run: docker build -t registry.localhost/rohanvirmani.ca:latest .
      working-directory: portfolio-minimal
    - run: docker push registry.localhost/rohanvirmani.ca:latest
      working-directory: portfolio-minimal
