name: Gatsby.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build -t registry.localhost/rohanvirmani.ca:latest .
      working-directory: portfolio-minimal
    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: rohanvirmani.ca # Your registry domain
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push registry.localhost/rohanvirmani.ca:latest
      working-directory: portfolio-minimal
