name: Gatsby.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: docker.rohanvirmani.ca # Your registry domain
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t rohanvirmani.ca/portfoliowebsite:latest .
        docker push rohanvirmani.ca/portfoliowebsite:latest
      working-directory: portfolio-minimal
